kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: todo-role-prod
  namespace: todo-app-prod-ns
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ['*']
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: todo-binding-prod
  namespace: todo-app-prod-ns
subjects:
  - kind: ServiceAccount
    name: todo-prod
    namespace: todo-app-ns
roleRef:
  kind: Role
  name: todo-role-prod
  apiGroup: rbac.authorization.k8s.io
