kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: todo-role
  namespace: todo-app-ns
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ['*']
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: todo-binding
  namespace: todo-app-ns
subjects:
  - kind: ServiceAccount
    name: todo-dev
    namespace: todo-app-ns
roleRef:
  kind: Role
  name: todo-role
  apiGroup: rbac.authorization.k8s.io
